# Generated by Django 4.1.1 on 2022-12-21 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do objetivo')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo')),
                ('objective_date', models.DateField(verbose_name='Data final do objetivo')),
                ('name', models.CharField(max_length=55, verbose_name='Nome')),
                ('color', models.CharField(choices=[('blue', 'BLUE'), ('light-blue', 'LIGHT_BLUE'), ('red', 'RED'), ('jigglypuff', 'JIGGLYPUFF'), ('pink', 'PINK'), ('yellow', 'YELLOW'), ('orange', 'ORANGE'), ('green', 'GREEN'), ('purple', 'PURPLE'), ('grey', 'GREY'), ('light-green', 'LIGHT_GREEN'), ('petrel', 'PETREL'), ('primer', 'PRIMER')], max_length=50, verbose_name='Cor da conta')),
                ('icon', models.CharField(choices=[('wallet2', 'WALLET'), ('house', 'HOUSE'), ('cart', 'CART'), ('bookmark-heart', 'BOOKMARK_HEART'), ('calendar-event', 'EVENT'), ('book', 'BOOK'), ('person', 'PERSON'), ('pin-map', 'MAP'), ('car-front', 'CAR'), ('person-video3', 'VIDEO'), ('geo-alt', 'GEO'), ('airplane', 'AIRPLANE'), ('bicycle', 'BICYCLE'), ('umbrella', 'UMBRELLA'), ('graph-up', 'ARROW'), ('justify-left', 'LIST'), ('pie-chart', 'CHART'), ('houses', 'HOUSES'), ('phone', 'PHONE'), ('display', 'DISPLAY'), ('controller', 'CONTROLLER'), ('three-dots', 'THREE_DOTS'), ('shop', 'SHOP'), ('heart', 'HEART'), ('file', 'FILE'), ('cart2', 'CART2'), ('truck', 'TRUNK'), ('star', 'STAR'), ('gift', 'GIFT'), ('minecart', 'MINICART')], max_length=50, verbose_name='Ícone')),
                ('status', models.CharField(choices=[('stopped', 'STOPPED'), ('active', 'ACTIVE'), ('concluded', 'CONCLUDED')], default='active', max_length=50, verbose_name='Status')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('deleted_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('stored', django.db.models.manager.Manager()),
            ],
        ),
    ]
