# Generated by Django 4.1.1 on 2022-12-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective', '0003_objective_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Descrição'),
        ),
    ]
