# Generated by Django 4.1.1 on 2022-12-07 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('icon', models.ImageField(upload_to='categories/', verbose_name='Ícone')),
                ('deleted_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bandeira',
                'verbose_name_plural': 'Bandeiras',
            },
            managers=[
                ('stored', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Limite')),
                ('invoice_closing', models.DateField(verbose_name='Dia de fechamento')),
                ('invoice_expiration', models.DateField(verbose_name='Dia do vencimento')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('default', models.BooleanField(default=False, verbose_name='Padrão')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cartão', to='accounts.account')),
                ('deleted_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bandeira', to='credit_card.flag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
            },
            managers=[
                ('stored', django.db.models.manager.Manager()),
            ],
        ),
    ]
