# Generated by Django 4.1.1 on 2022-12-07 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='financial_institution/', verbose_name='Logo')),
                ('deleted_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instituição Financeira',
                'verbose_name_plural': 'Instituições Financeiras',
            },
            managers=[
                ('stored', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo inicial')),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo atual')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('account_type', models.CharField(choices=[('checking_account', 'CHECKING_ACCOUNT'), ('money', 'MONEY'), ('savings', 'SAVINGS'), ('investments', 'INVESTMENTS'), ('others', 'OTHERS')], max_length=50, verbose_name='Tipo de conta')),
                ('color', models.CharField(choices=[('blue', 'BLUE'), ('red', 'RED'), ('jigglypuff', 'JIGGLYPUFF'), ('pink', 'PINK'), ('yellow', 'YELLOW'), ('orange', 'ORANGE'), ('green', 'GREEN'), ('purple', 'PURPLE'), ('petrel', 'PETREL'), ('primer', 'PRIMER')], max_length=50, verbose_name='Cor da conta')),
                ('default', models.BooleanField(default=False, verbose_name='Conta Padrão')),
                ('active', models.BooleanField(default=True, verbose_name='Conta ativa')),
                ('include_on_dashboard', models.BooleanField(default=True, verbose_name='Incluir na soma da tela inicial')),
                ('deleted_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('financial_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.financialinstitution', verbose_name='Instituição Financeira')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
            managers=[
                ('stored', django.db.models.manager.Manager()),
            ],
        ),
    ]
