# Generated by Django 4.1.1 on 2022-12-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='include_on_dashboard',
            field=models.BooleanField(default=True, verbose_name='Incluir na soma da tela inicial'),
        ),
    ]
