export const ENDPOINTS_CONSTANTS = {
  BASE_TRANSACTION_REST_URL: '/transacoes/rest',
  GET_TRANSACTION_LIST_FOR_AUTHENTICATED_USER_URL: 'transacoes',
  CREATE_TRANSACTION_FORM_URL: 'criar'
}

export const TRANSACTION_TYPE = {
  INCOME: 'income',
  EXPENSE: 'expense',
  CREDIT: 'credit',
  TRANSFER: 'transfer',
  OBJECTIVE: 'objective'
}

export const TRANSACTION_STORE_CONSTANTS = {
  MODULE_NAME: 'TransactionStore',
  GETTERS: {
    IS_LOADING: 'IS_LOADING',
    GET_TRANSACTION: 'GET_TRANSACTION',
    GET_LIST: 'GET_LIST'
  },
  MUTATIONS: {
    SET_LOADING: 'SET_LOADING',
    SET_TRANSACTION: 'SET_TRANSACTION',
    SET_LIST: 'SET_LIST'
  }
}

export const TRANSACTION_SUMMARY_STORE_CONSTANTS = {
  MODULE_NAME: 'TransactionSummaryStore',
  GETTERS: {
    IS_LOADING: 'IS_LOADING',
    GET_TRANSACTION_SUMMARY: 'GET_TRANSACTION_SUMMARY'
  },
  MUTATIONS: {
    SET_LOADING: 'SET_LOADING',
    SET_TRANSACTION_SUMMARY: 'SET_TRANSACTION_SUMMARY'
  }
}
