export const ENDPOINTS_CONSTANTS = {
  BASE_REST_URL: '/contas/rest',
  GET_ACCOUNT_LIST_FOR_AUTHENTICATED_USER_URL: 'contas/usuario'
}

export const ACCOUNT_STORE_CONSTANTS = {
  MODULE_NAME: 'AccountStore',
  GETTERS: {
    GET_ACCOUNT_LIST: 'GET_ACCOUNT_LIST'
  },
  MUTATIONS: {
    SET_ACCOUNT_LIST: 'SET_ACCOUNT_LIST'
  },
  ACTIONS: {
    LOAD_ACCOUNT_LIST: 'LOAD_ACCOUNT_LIST'
  }
}
