from enum import Enum


class Color(Enum):
    BLUE = 'blue'
    LIGHT_BLUE = 'light-blue'
    RED = 'red'
    JIGGLYPUFF = 'jigglypuff'
    PINK = 'pink'
    YELLOW = 'yellow'
    ORANGE = 'orange'
    GREEN = 'green'
    PURPLE = 'purple'
    GREY = 'grey'
    LIGHT_GREEN = 'light-green'
    PETREL = 'petrel'
    PRIMER = 'primer'


class Icon(Enum):
    WALLET = 'wallet2'
    HOUSE = 'house'
    CART = 'cart'
    BOOKMARK_HEART = 'bookmark-heart'
    EVENT = 'calendar-event'
    BOOK = 'book'
    PERSON = 'person'
    MAP = 'pin-map'
    CAR = 'car-front'
    VIDEO = 'person-video3'
    GEO = 'geo-alt'
    AIRPLANE = 'airplane'
    BICYCLE = 'bicycle'
    UMBRELLA = 'umbrella'
    ARROW = 'graph-up'
    LIST = 'justify-left'
    CHART = 'pie-chart'
    HOUSES = 'houses'
    PHONE = 'phone'
    DISPLAY = 'display'
    CONTROLLER = 'controller'
    THREE_DOTS = 'three-dots'
    SHOP = 'shop'
    HEART = 'heart'
    FILE = 'file'
    CART2 = 'cart2'
    TRUNK = 'truck'
    STAR = 'star'
    GIFT = 'gift'
    PINMAP = 'pin-map'
    MINICART = 'minecart'
