export const COLOR_OPTIONS = [
  { value: 'blue', name: 'Azul' },
  { value: 'light-blue', name: 'Azul claro' },
  { value: 'red', name: 'Vermelho' },
  { value: 'pink', name: 'Rosa' },
  { value: 'jigglypuff', name: 'Rosa claro' },
  { value: 'yellow', name: 'Amarelo' },
  { value: 'orange', name: 'Laranja' },
  { value: 'green', name: 'Verde' },
  { value: 'light-green', name: 'Verde claro' },
  { value: 'purple', name: 'Roxo' },
  { value: 'grey', name: 'Cinza' },
  { value: 'petrel', name: 'Cinza escuro' },
  { value: 'primer', name: 'Cinza escuro' }
]

export const ICON_OPTIONS = [
  { value: 'wallet2', name: '' },
  { value: 'house', name: '' },
  { value: 'cart', name: '' },
  { value: 'bookmark-heart', name: '' },
  { value: 'calendar-event', name: '' },
  { value: 'book', name: '' },
  { value: 'person', name: '' },
  { value: 'geo-alt', name: '' },
  { value: 'bicycle', name: '' },
  { value: 'umbrella', name: '' },
  { value: 'graph-up', name: '' },
  { value: 'justify-left', name: '' },
  { value: 'pie-chart', name: '' },
  { value: 'phone', name: '' },
  { value: 'display', name: '' },
  { value: 'controller', name: '' },
  { value: 'three-dots', name: '' },
  { value: 'shop', name: '' },
  { value: 'heart', name: '' },
  { value: 'file', name: '' },
  { value: 'cart2', name: '' },
  { value: 'truck', name: '' },
  { value: 'star', name: '' },
  { value: 'gift', name: '' },
  { value: 'pin-map', name: '' },
  { value: 'smartwatch', name: '' },
  { value: 'minecart', name: '' }
]
