# Generated by Django 4.1.1 on 2022-12-12 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_color'),
        ('transaction', '0003_alter_transaction_daily_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='credit_card',
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_account_transaction', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_transaction', to='accounts.account'),
        ),
    ]
