# Generated by Django 4.1.1 on 2022-12-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_remove_transaction_credit_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailybalance',
            name='expected_transfer',
        ),
        migrations.RemoveField(
            model_name='dailybalance',
            name='transfer',
        ),
        migrations.AlterField(
            model_name='dailybalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balanço'),
        ),
        migrations.AlterField(
            model_name='dailybalance',
            name='expected_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balanço previsto'),
        ),
    ]
