# Generated by Django 4.1.1 on 2022-12-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_remove_dailybalance_expected_transfer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='daily_balance',
        ),
        migrations.AddField(
            model_name='dailybalance',
            name='transactions',
            field=models.ManyToManyField(blank=True, null=True, to='transaction.transaction'),
        ),
    ]
