# Generated by Django 4.1.1 on 2022-12-12 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_remove_dailybalance_transactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='daily_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.dailybalance', verbose_name='Balanço diário'),
        ),
    ]
