# Generated by Django 4.1.1 on 2022-12-20 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='file',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ignore',
        ),
    ]
