# Generated by Django 4.1.1 on 2022-12-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_remove_transaction_store_remove_transaction_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='store',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='daily_balance',
        ),
        migrations.DeleteModel(
            name='DailyBalance',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
