# Generated by Django 4.1.1 on 2022-12-21 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_remove_transaction_installment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurrence',
            name='amout',
        ),
        migrations.RemoveField(
            model_name='recurrence',
            name='fixed',
        ),
        migrations.RemoveField(
            model_name='recurrence',
            name='repeat',
        ),
        migrations.AddField(
            model_name='transaction',
            name='fixed',
            field=models.BooleanField(default=False, verbose_name='Fixa'),
        ),
        migrations.AlterField(
            model_name='recurrence',
            name='repeat_amount',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(100, message='Deve ser um valor menor que 100')], verbose_name='Vezes'),
        ),
    ]
