# Generated by Django 4.1.1 on 2022-12-21 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0015_remove_recurrence_amout_remove_recurrence_fixed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrence',
            name='repeat_period',
            field=models.CharField(choices=[('everyday', 'EVERY_DAY'), ('weekly', 'WEEKLY'), ('monthly', 'MONTHLY'), ('annually', 'ANNUALLY'), ('every_day_week', 'EVERY_DAY_WEEK')], default='monthly', max_length=50, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_transaction', to='transaction.recurrence'),
        ),
    ]
