# Generated by Django 4.1.1 on 2022-12-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_alter_recurrence_repeat_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='fixed',
        ),
        migrations.AddField(
            model_name='recurrence',
            name='fixed',
            field=models.BooleanField(default=False, verbose_name='Fixa'),
        ),
    ]
