# Generated by Django 4.1.1 on 2022-12-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0017_remove_transaction_fixed_recurrence_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='installment',
            field=models.IntegerField(default=1, verbose_name='Prestação'),
        ),
    ]
